### ISSUE TITLE
Book Item Component

### ISSUE THREAD

**Issue by AdhamUsama25** [Eight-Horsepeople-of-the-Graduation/frontend#18]
**As a:** User
**When:** I see this component
**I Expect:** to see the book cover, name, author, (rating if exist)

---

**As a:** User
**When:** I click on the component
**I Expect:** to go to this book page

---

**As a:** User
**When:** I hover on this component
**I Expect:** an add to list button to be shown

**Comment by ranaagouda** [comment]
done
